using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;
using Microsoft.Toolkit.Services.MicrosoftGraph;
using System.Threading.Tasks;
using Microsoft.Graph;
using System.Net.Http;

// The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace QuickNotes
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            SetAuthState(false);

            // Load OAuth settings
            var oauthSettings = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("OAuth");
            var appId = oauthSettings.GetString("AppId");
            var scopes = oauthSettings.GetString("Scopes");

            if (string.IsNullOrEmpty(appId) || string.IsNullOrEmpty(scopes))
            {
                Notification.Show("Could not load OAuth Settings from resource file.");
            }
            else
            {
                // Initialize Graph
                MicrosoftGraphService.Instance.AuthenticationModel = MicrosoftGraphEnums.AuthenticationModel.V2;
                MicrosoftGraphService.Instance.Initialize(appId,
                    MicrosoftGraphEnums.ServicesToInitialize.UserProfile,
                    scopes.Split(' '));
            }
        }

        private void SetAuthState(bool isAuthenticated)
        {
            (App.Current as App).IsAuthenticated = isAuthenticated;
            if (isAuthenticated)
                ShowControlsForSignedInState();
            else
                ShowControlsForSignedOutState();
        }

        private void ShowControlsForSignedInState()
        {
            CreateQuickNoteButton.Visibility = Visibility.Visible;
            NoteTitleTextBox.Visibility = Visibility.Visible;
            SignInTextBlock.Visibility = Visibility.Collapsed;
        }

        private void ShowControlsForSignedOutState()
        {
            CreateQuickNoteButton.Visibility = Visibility.Collapsed;
            NoteTitleTextBox.Visibility = Visibility.Collapsed;
            SignInTextBlock.Visibility = Visibility.Visible;
        }

        private void Login_SignInCompleted(object sender, Microsoft.Toolkit.Uwp.UI.Controls.Graph.SignInEventArgs e)
        {
            // Set the auth state
            SetAuthState(true);
            // Reload the home page
        }

        private void Login_SignOutCompleted(object sender, EventArgs e)
        {
            // Set the auth state
            SetAuthState(false);
            // Reload the home page
        }

        private void CreateQuickNoteButton_Click(object sender, RoutedEventArgs e)
        {
            OneNoteAddPageHtml();
        }

        private void NoteTitleTextBox_KeyDown(object sender, KeyRoutedEventArgs e)
        {
            if (e.Key == Windows.System.VirtualKey.Enter)
            {
                OneNoteAddPageHtml();
            }
        }

        public async Task OneNoteAddPageHtml()
        {
            GraphServiceClient graphClient = MicrosoftGraphService.Instance.GraphProvider;
            string noteTitle = GetAndClearNoteTitle();
            NoteTitleTextBox.Focus(FocusState.Keyboard);

            try
            {
                // Get a page of OneNote sections.
                IOnenoteSectionsCollectionPage sectionPage = await graphClient.Me.Onenote.Sections.Request()
                    .Filter("displayName eq 'Quick Notes'")
                    .GetAsync();

                // Get a handle to the first section.
                string sectionId = sectionPage[0].Id;

                // Get the request URL for adding a page. 
                string requestUrl = graphClient.Me.Onenote.Sections[sectionId].Pages.Request().RequestUrl;

                string htmlBody = String.Concat(
                    @"<!DOCTYPE html><html><head><title>",
                    noteTitle,
                    @"</title></head><body>Generated by QuickNotes</body></html> "
                    );

                // Create the request message and add the content.
                HttpRequestMessage hrm = new HttpRequestMessage(HttpMethod.Post, requestUrl);
                hrm.Content = new StringContent(htmlBody, System.Text.Encoding.UTF8, "text/html");

                // Authenticate (add access token) our HttpRequestMessage
                await graphClient.AuthenticationProvider.AuthenticateRequestAsync(hrm);

                // Send the request and get the response.
                HttpResponseMessage response = await graphClient.HttpProvider.SendAsync(hrm);

                // Get the OneNote page that we created.
                if (response.IsSuccessStatusCode)
                {
                    // Deserialize into OneNotePage object.
                    var content = await response.Content.ReadAsStringAsync();
                    OnenotePage page = graphClient.HttpProvider.Serializer.DeserializeObject<OnenotePage>(content);
                }
                else
                    throw new ServiceException(
                        new Error
                        {
                            Code = response.StatusCode.ToString(),
                            Message = await response.Content.ReadAsStringAsync()
                        });
            }
            catch (Exception e)
            {
                throw (e);
            }
        }

        private string GetAndClearNoteTitle()
        {
            string noteTitle = NoteTitleTextBox.Text;
            NoteTitleTextBox.Text = string.Empty;
            return noteTitle;
        }
    }
}
